In [1]:
from mysql import connector
from mysql.connector import Error

In [2]:
%load_ext sql

In [3]:
%sql mysql://root:1998@localhost/stocks

In [4]:
try:
    connection = connector.connect(host='localhost',database='stocks',user='root', password='1998',auth_plugin='mysql_native_password')
    if connection.is_connected():
        db_Info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_Info)
        cursor = connection.cursor()
        value = cursor.execute("SELECT COUNT(*) FROM apollo;")
        record =cursor.fetchone()
        print("You're connected to database: ", record)
        print(type(value))

except Error as e:
    print("Error while connecting to MySQL", e)
finally:
    if (connection.is_connected()):
        cursor.close()
        connection.close()
        print("MySQL connection is closed")
        print(value)

Connected to MySQL Server version  8.0.21
You're connected to database:  (375,)
<class 'NoneType'>
MySQL connection is closed
None

In [5]:
def insertVariblesIntoTable(Date, Open, Low, High, Close, Adj_close,Volume):
    try:
        connection = connector.connect(host='localhost',
                                             database='stocks',
                                             user='root',
                                             password='1998')
        cursor = connection.cursor()
        mySql_insert_query = '''INSERT INTO apollo (Date, Open, Low, High, Close, Adj_Close,Volume) 
                                VALUES (%s, %s, %s, %s, %s, %s,%s)'''

        recordTuple = (Date, Open, Low, High, Close, Adj_close,Volume)
        cursor.execute(mySql_insert_query, recordTuple)
        connection.commit()
        print("Record inserted successfully into Laptop table")

    except connector.Error as error:
        print("Failed to insert into MySQL table {}".format(error))

    finally:
        if (connection.is_connected()):
            cursor.close()
            connection.close()
            print("MySQL connection is closed")

In [6]:
%sql Truncate Table apollo

 * mysql://root:***@localhost/stocks
0 rows affected.

[]

In [7]:
#insertVariblesIntoTable("1998-8-11",260.5,298.02,230.35,290.36,295.0,987)

In [8]:
import yfinance as yf
import time

In [ ]:
minutes = 1
threshold = len(yf.download("APOLLOTYRE.NS",period="1d",interval="1m"))
print("threshold:",threshold)
value = %sql SELECT COUNT('Date') FROM apollo
while True:
    if value[0][0] < threshold:
        ################################################################################
        raydaily = yf.download("APOLLOTYRE.NS",period="1d",interval="1m")

        insertflag = len(raydaily)
        print("insertflag:",insertflag)
                ############################################################################
        ############################################################################
        raydaily["Volume"] = raydaily["Volume"].astype(float)
        for rows in range(0,threshold):
            insertVariblesIntoTable(raydaily.index[rows],raydaily["Open"][rows],
                                    raydaily["Low"][rows],raydaily["High"][rows],
                                    raydaily["Close"][rows],raydaily["Adj Close"][rows],raydaily["Volume"][rows])
            
        #time.sleep(60) # Delay for every 60 secs (60 seconds).
        value = %sql SELECT COUNT('Date') FROM apollo

        #print("Time passed {} minutes".format(minutes))
        #minutes += 1
        
        
    else:
        #################################################################################
        raydaily = yf.download("APOLLOTYRE.NS",period="1d",interval="1m")

        insertflag = len(raydaily)
        print("insertflag:",insertflag)
        
        ##################################################################################
        ##################################################################################
        raydaily["Volume"] = raydaily["Volume"].astype(float)
        if insertflag > value[0][0]:
            extra = insertflag - value[0][0]
            for rows in range(-(extra),0):
                insertVariblesIntoTable(raydaily.index[rows],raydaily["Open"][rows],
                                        raydaily["Low"][rows],raydaily["High"][rows],
                                        raydaily["Close"][rows],raydaily["Adj Close"][rows],raydaily["Volume"][rows])


        time.sleep(60) # Delay for every 60 secs (60 seconds).
        value = %sql SELECT COUNT('Date') FROM apollo

        print("Time passed {} minutes".format(minutes))
        minutes += 1

[*********************100%***********************]  1 of 1 completed
threshold: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
[*********************100%***********************]  1 of 1 completed
insertflag: 375
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table

MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table

MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table

MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
Record inserted successfully into Laptop table
MySQL connection is closed
 * mysql://root:***@localhost/stocks
1 rows affected.
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 1 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 2 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 3 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 4 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 5 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 6 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 7 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 8 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 9 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 10 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 11 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 12 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 13 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 14 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 15 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 16 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 17 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 18 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 19 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 20 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 21 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 22 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 23 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 24 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 25 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 26 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 27 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 28 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 29 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 30 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 31 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 32 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 33 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 34 minutes

[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 35 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 36 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 37 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 38 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 39 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 40 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 41 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 42 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 43 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 44 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 45 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 46 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 47 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 48 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 49 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 50 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375
 * mysql://root:***@localhost/stocks
1 rows affected.
Time passed 51 minutes
[*********************100%***********************]  1 of 1 completed
insertflag: 375

In [6]:
#%sql Truncate Table apollo

 * mysql://root:***@localhost/stocks
0 rows affected.

[]